### ISSUE TITLE
Makefile improvement

### ISSUE THREAD

**Issue by saladuit** [tmatis/ft_mallocator#32]
```
-malloc_test: $(OBJS) $(MAIN_OBJ) $(LIBFT)
-       @$(MAKE) DEBUG=1
-       $(CC) $(CFLAGS) $^ -fsanitize=undefined -rdynamic -o $@ $(INCLUDE_FLAGS) -L../ft_mallocator -lmallocator
+malloc_test: debug
+       $(CC) $(CFLAGS) $(OBJS) $(MAIN_OBJ) $(LIBFT) -fsanitize=undefined -rdynamic -o $@ $(INCLUDE_FLAGS) $(LIB_FLAGS) -L. -lmallocator
```
The malloc_test rule should be dependent on a rule like debug. This enforces the object files to be created with -g symbols.  The debug rule and CFLAGS  variable should look something like this:
```
CFLAGS			=-Wall -Wextra -Werror$(if $(DEBUG), -g -D DEBUG=1)$(if $(FSAN), -g -D DEBUG=1 -fsanitize=address)
debug:
	@$(MAKE) DEBUG=1

rebug: fclean
	@$(MAKE) debug
```

**Comment by saladuit** [comment]
Good job on the program though! I use it more often nowadays!

**Comment by froz42** [comment]
Hello thank you for you issue, I'm currently working on a new version of this program that does not need any Makefile modification and will work a bit like valgrind, so I would not work on this issue but feel free so submit a merge requestif you want I would review with pleasure

**Comment by saladuit** [comment]
Hey sorry! 
I'd completely missed your reponse. In that case I don't want to break. 
I'm really curious for your update!
Will there also be a feature were you can pass commands from the stdin or let's say a file?
For example, I'm currently using your project to test minishell for leaks, but it is quite cumbersome to pass in all of the variations of commands one by one. 
I'd like to hear your thoughts!
