### ISSUE TITLE
ARGS doesn't not support "

### ISSUE THREAD

**Issue by ThomasRobertson** [tmatis/ft_mallocator#4]
Hi !

Thanks a lot for your tool, it's been really useful :)

I've been trying to test my project pipex and just realised that I cannot put any " inside the ARGS field in config.sh.

`ARGS="file1 "sleep 1" cat file2"` just become `file1 ` and cannot fetch any route. Removing the " or switching to ' solve the problem.

I don't know if you can fix that, but maybe putting a warning would help people with this issue (especially on pipex).

**Comment by froz42** [comment]
Hello, if you edit the file manually , you have to escape the `"`  with an `\`
